version: '3.8'

services:
  backend:
    build: ./Back-EndProyectoFinal2025
    ports:
      - "8000:8000"
    volumes:
      - ./Back-EndProyectoFinal2025:/app
    environment:
      - DB_ENGINE=mysql
      - POSTGRES_DB=dbautogestion-P
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - MYSQL_DATABASE=dbautogestion-M
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MSSQL_DATABASE=dbautogestion-S
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=Abc123$%
      - MSSQL_HOST=mssql-db
      - MSSQL_PORT=1433
    depends_on:
      - postgres-db
      - mysql-db
      - mssql-db

  frontend:
    build: ./Front-end-Proyecto-2025
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api/
    depends_on:
      - backend

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: dbautogestion-P
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dbautogestion-M
    ports:
      - "3306:3306"

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Abc123$%
      MSSQL_PID: Express
    ports:
      - "1433:1433"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend