# Generated by Django 4.2.23 on 2025-08-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
