# Generated by Django 4.2.23 on 2025-08-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codeCenter', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFicha', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractType', models.CharField(max_length=50)),
                ('contractStartDate', models.DateField()),
                ('contractEndDate', models.DateField()),
                ('knowledgeArea', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProgram', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('typeProgram', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codeRegional', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=255)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codeSede', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phoneSede', models.CharField(max_length=20)),
                ('emailContact', models.EmailField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
