FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-dev build-essential \
    default-libmysqlclient-dev libpq-dev unixodbc-dev pkg-config \
    netcat

WORKDIR /app

COPY . /app

RUN pip3 install --no-cache-dir -r requirements.txt

COPY wait-for-mysql.sh /wait-for-mysql.sh
RUN chmod +x /wait-for-mysql.sh

EXPOSE 8000

CMD ["/wait-for-mysql.sh", "python3", "manage.py", "runserver", "0.0.0.0:8000"]